"""
CyberTwin SOC - Scoring & Risk Engine
========================================
Calculates detection, coverage, response, visibility, and overall maturity
scores based on simulation results. Assigns risk levels, maturity
classifications, and generates actionable improvement recommendations.
"""

from __future__ import annotations

from typing import Any


class ScoringEngine:
    """Computes security posture scores from simulation and detection results.

    Score dimensions:
        - **detection_score**: % of attack phases that triggered at least one alert
        - **coverage_score**: % of expected MITRE techniques that were detected
        - **response_score**: based on mean time-to-detect relative to the attack window
        - **visibility_score**: % of log sources that produced relevant events
        - **overall_score**: weighted combination of the above

    The engine also assigns a maturity level and risk level based on the overall score.
    """

    # Weights used for the composite score
    _WEIGHTS = {
        "detection": 0.35,
        "coverage": 0.30,
        "response": 0.15,
        "visibility": 0.20,
    }

    # Log source categories considered for visibility
    _EXPECTED_LOG_SOURCES = {
        "authentication", "process", "file_access", "network",
        "firewall", "dns", "web_access", "email", "application",
        "database", "security", "ids",
    }

    def calculate_scores(
        self,
        scenario: dict[str, Any],
        alerts: list[dict[str, Any]],
        logs: list[dict[str, Any]],
        mitre_expected: list[str] | None = None,
    ) -> dict[str, Any]:
        """Run the full scoring pipeline and return a result dictionary.

        Parameters
        ----------
        scenario : dict
            The attack scenario definition (must contain ``phases`` and
            ``mitre_techniques_summary``).
        alerts : list[dict]
            Alerts generated by the detection engine.
        logs : list[dict]
            All log events produced during the simulation.
        mitre_expected : list[str], optional
            Override list of expected MITRE technique IDs.
        """
        phases = scenario.get("phases", [])
        expected_techniques = mitre_expected or scenario.get("mitre_techniques_summary", [])

        detection = self._score_detection(phases, alerts)
        coverage = self._score_coverage(expected_techniques, alerts)
        response = self._score_response(phases, alerts, logs)
        visibility = self._score_visibility(logs)

        overall = round(
            detection * self._WEIGHTS["detection"]
            + coverage * self._WEIGHTS["coverage"]
            + response * self._WEIGHTS["response"]
            + visibility * self._WEIGHTS["visibility"],
            1,
        )

        risk_level = self._risk_level(overall)
        maturity = self._maturity_level(overall)

        return {
            "detection_score": round(detection, 1),
            "coverage_score": round(coverage, 1),
            "response_score": round(response, 1),
            "visibility_score": round(visibility, 1),
            "overall_score": overall,
            "risk_level": risk_level,
            "maturity_level": maturity,
            "details": {
                "phases_total": len(phases),
                "phases_detected": self._detected_phase_count(phases, alerts),
                "techniques_expected": len(expected_techniques),
                "techniques_detected": len(self._detected_techniques(expected_techniques, alerts)),
                "techniques_missed": list(
                    set(expected_techniques) - self._detected_techniques(expected_techniques, alerts)
                ),
                "mean_time_to_detect": self._mean_ttd(phases, alerts, logs),
                "log_sources_observed": list(self._observed_sources(logs)),
                "log_sources_expected": list(self._EXPECTED_LOG_SOURCES),
            },
            "recommendations": self._generate_recommendations(
                detection, coverage, response, visibility, phases, alerts, expected_techniques
            ),
        }

    # ------------------------------------------------------------------
    # Sub-scores
    # ------------------------------------------------------------------

    def _score_detection(self, phases: list[dict], alerts: list[dict]) -> float:
        """Percentage of attack phases that triggered >=1 alert."""
        if not phases:
            return 0.0
        detected = self._detected_phase_count(phases, alerts)
        return (detected / len(phases)) * 100

    def _score_coverage(self, expected: list[str], alerts: list[dict]) -> float:
        """Percentage of expected MITRE techniques covered by alerts."""
        if not expected:
            return 0.0
        detected = self._detected_techniques(expected, alerts)
        return (len(detected) / len(expected)) * 100

    def _score_response(
        self, phases: list[dict], alerts: list[dict], logs: list[dict],
    ) -> float:
        """Score based on mean time-to-detect (lower is better).

        Heuristic brackets (seconds):
            <=60 → 100,  <=300 → 80,  <=600 → 60,  <=1800 → 40,  >1800 → 20
        If no alerts triggered → 0.
        """
        ttd = self._mean_ttd(phases, alerts, logs)
        if ttd is None:
            return 0.0
        if ttd <= 60:
            return 100.0
        if ttd <= 300:
            return 80.0
        if ttd <= 600:
            return 60.0
        if ttd <= 1800:
            return 40.0
        return 20.0

    def _score_visibility(self, logs: list[dict]) -> float:
        """Percentage of expected log source categories observed."""
        if not self._EXPECTED_LOG_SOURCES:
            return 0.0
        observed = self._observed_sources(logs)
        return (len(observed & self._EXPECTED_LOG_SOURCES) / len(self._EXPECTED_LOG_SOURCES)) * 100

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _technique_matches(phase_tid: str, alert_tid: str) -> bool:
        """Check if techniques match, including parent-child relationships.
        e.g., T1110 matches T1110.001, and T1110.001 matches T1110.
        """
        if not phase_tid or not alert_tid:
            return False
        if phase_tid == alert_tid:
            return True
        # Parent matches child: T1110 matches T1110.001
        if alert_tid.startswith(phase_tid + ".") or phase_tid.startswith(alert_tid + "."):
            return True
        # Same parent: T1110.001 and T1110 share base
        base_phase = phase_tid.split(".")[0]
        base_alert = alert_tid.split(".")[0]
        return base_phase == base_alert

    @staticmethod
    def _detected_phase_count(phases: list[dict], alerts: list[dict]) -> int:
        alert_techniques = {a.get("technique_id") for a in alerts if a.get("technique_id")}
        count = 0
        for p in phases:
            ptid = p.get("technique_id", "")
            if any(
                ScoringEngine._technique_matches(ptid, atid)
                for atid in alert_techniques
            ):
                count += 1
        return count

    @staticmethod
    def _detected_techniques(expected: list[str], alerts: list[dict]) -> set[str]:
        alert_techniques = {a.get("technique_id") for a in alerts if a.get("technique_id")}
        detected = set()
        for exp in expected:
            if any(ScoringEngine._technique_matches(exp, atid) for atid in alert_techniques):
                detected.add(exp)
        return detected

    @staticmethod
    def _observed_sources(logs: list[dict]) -> set[str]:
        return {l.get("log_source", "") for l in logs if l.get("log_source")}

    @staticmethod
    def _mean_ttd(
        phases: list[dict], alerts: list[dict], logs: list[dict],
    ) -> float | None:
        """Estimate mean time-to-detect in seconds.

        Uses the difference between the earliest log with a matching
        ``technique_id`` and the first alert with that technique.
        """
        from datetime import datetime

        def _parse(ts: str) -> datetime | None:
            for fmt in ("%Y-%m-%dT%H:%M:%S.%fZ", "%Y-%m-%dT%H:%M:%S.%f",
                        "%Y-%m-%dT%H:%M:%S", "%Y-%m-%d %H:%M:%S"):
                try:
                    return datetime.strptime(ts, fmt)
                except (ValueError, TypeError):
                    continue
            return None

        technique_ids = {p.get("technique_id") for p in phases if p.get("technique_id")}
        if not technique_ids:
            return None

        # Earliest malicious log per technique
        first_log: dict[str, datetime] = {}
        for l in logs:
            tid = l.get("technique_id")
            if tid not in technique_ids:
                continue
            ts = _parse(l.get("timestamp", ""))
            if ts and (tid not in first_log or ts < first_log[tid]):
                first_log[tid] = ts

        # Earliest alert per technique
        first_alert: dict[str, datetime] = {}
        for a in alerts:
            tid = a.get("technique_id")
            if tid not in technique_ids:
                continue
            ts = _parse(a.get("timestamp", ""))
            if ts and (tid not in first_alert or ts < first_alert[tid]):
                first_alert[tid] = ts

        deltas: list[float] = []
        for tid in technique_ids:
            if tid in first_log and tid in first_alert:
                delta = (first_alert[tid] - first_log[tid]).total_seconds()
                deltas.append(max(delta, 0))

        return round(sum(deltas) / len(deltas), 1) if deltas else None

    # ------------------------------------------------------------------
    # Risk & maturity classification
    # ------------------------------------------------------------------

    @staticmethod
    def _risk_level(overall: float) -> str:
        if overall >= 80:
            return "Low"
        if overall >= 60:
            return "Medium"
        if overall >= 40:
            return "High"
        return "Critical"

    @staticmethod
    def _maturity_level(overall: float) -> str:
        if overall >= 85:
            return "Optimized"
        if overall >= 70:
            return "Managed"
        if overall >= 50:
            return "Defined"
        if overall >= 30:
            return "Developing"
        return "Initial"

    # ------------------------------------------------------------------
    # Recommendations
    # ------------------------------------------------------------------

    @staticmethod
    def _generate_recommendations(
        detection: float, coverage: float, response: float,
        visibility: float, phases: list, alerts: list,
        expected_techniques: list,
    ) -> list[dict[str, str]]:
        recs: list[dict[str, str]] = []

        if detection < 50:
            recs.append({
                "priority": "critical",
                "category": "Detection",
                "title": "Improve attack-phase detection coverage",
                "description": (
                    "Less than half of the attack phases triggered an alert. "
                    "Review detection rules and add signatures for the missed phases."
                ),
            })

        if coverage < 60:
            missed = set(expected_techniques) - {
                a.get("technique_id") for a in alerts if a.get("technique_id")
            }
            recs.append({
                "priority": "high",
                "category": "MITRE Coverage",
                "title": "Expand MITRE ATT&CK technique coverage",
                "description": (
                    f"Missed techniques: {', '.join(sorted(missed))}. "
                    "Create detection rules or analytics for these techniques."
                ),
            })

        if response < 40:
            recs.append({
                "priority": "high",
                "category": "Response Time",
                "title": "Reduce mean time-to-detect (MTTD)",
                "description": (
                    "The average detection delay is too high. Consider real-time "
                    "correlation rules and automated alert triage to speed up response."
                ),
            })

        if visibility < 60:
            recs.append({
                "priority": "medium",
                "category": "Visibility",
                "title": "Increase log-source diversity",
                "description": (
                    "Several log categories are missing from the telemetry pipeline. "
                    "Ensure all critical sources (endpoint, network, identity, application) "
                    "are shipping logs to the SIEM."
                ),
            })

        if not recs:
            recs.append({
                "priority": "low",
                "category": "Maintenance",
                "title": "Continue regular assessment",
                "description": (
                    "Current scores are satisfactory. Schedule periodic simulations "
                    "to maintain and improve the security posture."
                ),
            })

        return recs
