"""Pre-built CyberTwin SOC detection rule catalogue.

Each :class:`DetectionRule` instance ties a condition function (defined in
``conditions.py``) to MITRE ATT&CK metadata and engine parameters. The
ordered list ``DETECTION_RULES`` is the source of truth consumed by
``backend.detection.engine`` and ``backend.coverage.calculator``.
"""

from __future__ import annotations

from .base import DetectionRule
from .conditions import (
    _account_creation,
    _archive_creation,
    _as_rep_roasting,
    _bulk_file_access,
    _bulk_file_deletion,
    _cloud_exfiltration,
    _cloud_imds_abuse,
    _cobalt_strike_beacon,
    _container_escape,
    _credential_dumping,
    _credential_harvesting,
    _crontab_modification,
    _cryptominer_detection,
    _data_staging,
    _database_dump,
    _dcsync_attack,
    _dga_detection,
    _discovery_enumeration,
    _dns_tunneling_entropy,
    _exploit_privesc,
    _golden_ticket,
    _kerberoasting,
    _large_outbound_transfer,
    _log_tampering,
    _login_after_failures,
    _login_external_ip,
    _lolbas_execution,
    _multiple_failed_logins,
    _off_hours_file_access,
    _off_hours_login,
    _pass_the_hash,
    _phishing_email,
    _port_scan,
    _privilege_escalation,
    _process_injection,
    _psexec_wmi_lateral,
    _ransomware_indicators,
    _robocopy_bulk_copy,
    _sensitive_file_access,
    _shadow_copy_deletion,
    _ssh_brute_force,
    _supply_chain_attack,
    _suspicious_process,
    _unusual_dns,
    _usb_device,
    _web_shell,
)


DETECTION_RULES: list[DetectionRule] = [
    DetectionRule(
        rule_id="RULE-001",
        name="Multiple Failed Login Attempts",
        description="More than 5 failed login attempts from the same user within 5 minutes.",
        severity="high",
        tactic="Credential Access",
        technique_id="T1110",
        technique_name="Brute Force",
        condition=_multiple_failed_logins,
        threshold=5,
        time_window_seconds=300,
    ),
    DetectionRule(
        rule_id="RULE-002",
        name="Successful Login After Multiple Failures",
        description="A successful login following 3 or more consecutive failures for the same user.",
        severity="high",
        tactic="Credential Access",
        technique_id="T1110",
        technique_name="Brute Force",
        condition=_login_after_failures,
        threshold=3,
    ),
    DetectionRule(
        rule_id="RULE-003",
        name="Login From External IP",
        description="Successful authentication originating from a non-RFC-1918 IP address.",
        severity="medium",
        tactic="Initial Access",
        technique_id="T1078",
        technique_name="Valid Accounts",
        condition=_login_external_ip,
    ),
    DetectionRule(
        rule_id="RULE-004",
        name="Off-Hours Login",
        description="Successful login detected outside normal business hours (before 06:00 or after 22:00).",
        severity="medium",
        tactic="Initial Access",
        technique_id="T1078",
        technique_name="Valid Accounts",
        condition=_off_hours_login,
    ),
    DetectionRule(
        rule_id="RULE-005",
        name="Port Scan Detected",
        description="More than 10 distinct destination ports contacted from the same source within 60 seconds.",
        severity="high",
        tactic="Discovery",
        technique_id="T1046",
        technique_name="Network Service Discovery",
        condition=_port_scan,
        threshold=10,
        time_window_seconds=60,
    ),
    DetectionRule(
        rule_id="RULE-006",
        name="SSH Brute Force",
        description="More than 20 SSH authentication failures from the same source in 10 minutes.",
        severity="critical",
        tactic="Credential Access",
        technique_id="T1110.001",
        technique_name="Brute Force: Password Guessing",
        condition=_ssh_brute_force,
        threshold=20,
        time_window_seconds=600,
    ),
    DetectionRule(
        rule_id="RULE-007",
        name="Privilege Escalation Command",
        description="Execution of privilege escalation utilities (sudo, su, runas, pkexec).",
        severity="medium",
        tactic="Privilege Escalation",
        technique_id="T1548",
        technique_name="Abuse Elevation Control Mechanism",
        condition=_privilege_escalation,
    ),
    DetectionRule(
        rule_id="RULE-008",
        name="Suspicious Process Execution",
        description="Reverse shell, encoded command, or living-off-the-land binary execution detected.",
        severity="critical",
        tactic="Execution",
        technique_id="T1059",
        technique_name="Command and Scripting Interpreter",
        condition=_suspicious_process,
    ),
    DetectionRule(
        rule_id="RULE-009",
        name="Large Outbound Data Transfer",
        description="Single outbound network flow exceeding 100 MB, possible data exfiltration.",
        severity="high",
        tactic="Exfiltration",
        technique_id="T1048",
        technique_name="Exfiltration Over Alternative Protocol",
        condition=_large_outbound_transfer,
        threshold=104857600,
    ),
    DetectionRule(
        rule_id="RULE-010",
        name="Sensitive File Access",
        description="Access to sensitive system files (shadow, SAM, SSH keys, credentials).",
        severity="high",
        tactic="Credential Access",
        technique_id="T1552",
        technique_name="Unsecured Credentials",
        condition=_sensitive_file_access,
    ),
    DetectionRule(
        rule_id="RULE-011",
        name="USB Device Connection",
        description="A USB storage device was connected to a monitored host.",
        severity="low",
        tactic="Initial Access",
        technique_id="T1091",
        technique_name="Replication Through Removable Media",
        condition=_usb_device,
    ),
    DetectionRule(
        rule_id="RULE-012",
        name="Unusual DNS Query",
        description="DNS query with suspicious TLD, long label, or TXT record type indicating possible tunnelling or C2.",
        severity="medium",
        tactic="Command and Control",
        technique_id="T1071.004",
        technique_name="Application Layer Protocol: DNS",
        condition=_unusual_dns,
    ),
    DetectionRule(
        rule_id="RULE-013",
        name="Web Shell Detected",
        description="Indicators of web shell upload or execution observed in web-access or process logs.",
        severity="critical",
        tactic="Persistence",
        technique_id="T1505.003",
        technique_name="Server Software Component: Web Shell",
        condition=_web_shell,
    ),
    DetectionRule(
        rule_id="RULE-014",
        name="Scheduled Task / Crontab Modification",
        description="Creation or modification of crontab entries or Windows scheduled tasks.",
        severity="medium",
        tactic="Persistence",
        technique_id="T1053",
        technique_name="Scheduled Task/Job",
        condition=_crontab_modification,
    ),
    DetectionRule(
        rule_id="RULE-015",
        name="Bulk File Deletion",
        description="More than 10 file deletion events from the same user within 60 seconds.",
        severity="high",
        tactic="Impact",
        technique_id="T1485",
        technique_name="Data Destruction",
        condition=_bulk_file_deletion,
        threshold=10,
        time_window_seconds=60,
    ),

    # --- NEW RULES for improved detection coverage ---

    DetectionRule(
        rule_id="RULE-016",
        name="Phishing Email Detected",
        description="Inbound email with suspicious indicators: failed SPF/DKIM, high spam score, or phishing attachment.",
        severity="high",
        tactic="Initial Access",
        technique_id="T1566",
        technique_name="Phishing",
        condition=_phishing_email,
    ),
    DetectionRule(
        rule_id="RULE-017",
        name="Credential Dumping Detected",
        description="Credential dumping tool execution detected (Mimikatz, procdump targeting LSASS, secretsdump).",
        severity="critical",
        tactic="Credential Access",
        technique_id="T1003",
        technique_name="OS Credential Dumping",
        condition=_credential_dumping,
    ),
    DetectionRule(
        rule_id="RULE-018",
        name="DCSync Attack Detected",
        description="Directory replication request from non-domain controller, indicating DCSync credential theft.",
        severity="critical",
        tactic="Credential Access",
        technique_id="T1003.006",
        technique_name="OS Credential Dumping: DCSync",
        condition=_dcsync_attack,
    ),
    DetectionRule(
        rule_id="RULE-019",
        name="PsExec / WMI Lateral Movement",
        description="Lateral movement via PsExec service, WMI execution, or admin share access detected.",
        severity="high",
        tactic="Lateral Movement",
        technique_id="T1021.002",
        technique_name="Remote Services: SMB/Windows Admin Shares",
        condition=_psexec_wmi_lateral,
    ),
    DetectionRule(
        rule_id="RULE-020",
        name="Cryptocurrency Miner Detected",
        description="Cryptocurrency miner process or mining pool connection detected (XMRig, Stratum protocol).",
        severity="high",
        tactic="Impact",
        technique_id="T1496",
        technique_name="Resource Hijacking",
        condition=_cryptominer_detection,
    ),
    DetectionRule(
        rule_id="RULE-021",
        name="Database Dump Detected",
        description="Database dump command execution detected (pg_dump, mysqldump, pg_dumpall).",
        severity="high",
        tactic="Collection",
        technique_id="T1005",
        technique_name="Data from Local System",
        condition=_database_dump,
    ),
    DetectionRule(
        rule_id="RULE-022",
        name="Data Archive Creation",
        description="Data archiving with compression or encryption detected (7-Zip, RAR, encrypted archives).",
        severity="medium",
        tactic="Collection",
        technique_id="T1560.001",
        technique_name="Archive Collected Data: Archive via Utility",
        condition=_archive_creation,
    ),
    DetectionRule(
        rule_id="RULE-023",
        name="Cloud Storage Exfiltration",
        description="Data upload to personal cloud storage or email service detected (Google Drive, Mega, ProtonMail).",
        severity="high",
        tactic="Exfiltration",
        technique_id="T1567.002",
        technique_name="Exfiltration Over Web Service: Exfiltration to Cloud Storage",
        condition=_cloud_exfiltration,
    ),
    DetectionRule(
        rule_id="RULE-024",
        name="Off-Hours File Access",
        description="Suspicious file access activity detected outside normal business hours (before 08:00 or after 18:00).",
        severity="medium",
        tactic="Collection",
        technique_id="T1005",
        technique_name="Data from Local System",
        condition=_off_hours_file_access,
    ),
    DetectionRule(
        rule_id="RULE-025",
        name="Bulk File Access",
        description="More than 5 file read/copy operations from the same user within 60 seconds.",
        severity="medium",
        tactic="Collection",
        technique_id="T1074.001",
        technique_name="Data Staged: Local Data Staging",
        condition=_bulk_file_access,
        threshold=5,
        time_window_seconds=60,
    ),
    DetectionRule(
        rule_id="RULE-026",
        name="Log Tampering / Anti-Forensics",
        description="Event log clearing, secure wiping, or anti-forensics tool usage detected.",
        severity="critical",
        tactic="Defense Evasion",
        technique_id="T1070.004",
        technique_name="Indicator Removal: File Deletion",
        condition=_log_tampering,
    ),
    DetectionRule(
        rule_id="RULE-027",
        name="Supply Chain Compromise",
        description="Package manager spawning shell or downloading suspicious payload detected.",
        severity="critical",
        tactic="Initial Access",
        technique_id="T1195.002",
        technique_name="Supply Chain Compromise: Compromise Software Supply Chain",
        condition=_supply_chain_attack,
    ),
    DetectionRule(
        rule_id="RULE-028",
        name="Active Directory Enumeration",
        description="AD reconnaissance tools detected: ADFind, SharpHound, BloodHound, Rubeus, nltest.",
        severity="high",
        tactic="Discovery",
        technique_id="T1087.002",
        technique_name="Account Discovery: Domain Account",
        condition=_discovery_enumeration,
    ),
    DetectionRule(
        rule_id="RULE-029",
        name="Privilege Escalation Exploit",
        description="Known privilege escalation exploit pattern detected (PwnKit, kernel exploit, UID change to root).",
        severity="critical",
        tactic="Privilege Escalation",
        technique_id="T1068",
        technique_name="Exploitation for Privilege Escalation",
        condition=_exploit_privesc,
    ),
    DetectionRule(
        rule_id="RULE-030",
        name="Credential Harvesting via Phishing",
        description="Credential harvesting through fake login portal or OAuth abuse detected.",
        severity="high",
        tactic="Credential Access",
        technique_id="T1556",
        technique_name="Modify Authentication Process",
        condition=_credential_harvesting,
    ),
    DetectionRule(
        rule_id="RULE-031",
        name="Cobalt Strike Beacon Activity",
        description="Cobalt Strike beacon or C2 implant activity detected (DLL sideloading, beacon traffic).",
        severity="critical",
        tactic="Command and Control",
        technique_id="T1059.003",
        technique_name="Command and Scripting Interpreter: Windows Command Shell",
        condition=_cobalt_strike_beacon,
    ),
    DetectionRule(
        rule_id="RULE-032",
        name="Sensitive Data Staging",
        description="Access to sensitive files (salaries, PII, strategic documents) indicating data staging for exfiltration.",
        severity="high",
        tactic="Collection",
        technique_id="T1005",
        technique_name="Data from Local System",
        condition=_data_staging,
    ),
    DetectionRule(
        rule_id="RULE-033",
        name="Bulk File Copy Tool",
        description="Bulk file copy tool usage detected (robocopy, xcopy with recursive flags).",
        severity="medium",
        tactic="Collection",
        technique_id="T1074.001",
        technique_name="Data Staged: Local Data Staging",
        condition=_robocopy_bulk_copy,
    ),
    DetectionRule(
        rule_id="RULE-034",
        name="Suspicious Account Creation",
        description="New user account created, potentially for persistence or backdoor access.",
        severity="high",
        tactic="Persistence",
        technique_id="T1136",
        technique_name="Create Account",
        condition=_account_creation,
    ),

    # --- ENTERPRISE RULES (RULE-035 to RULE-046) ---

    DetectionRule(
        rule_id="RULE-035",
        name="Kerberoasting Attack Detected",
        description="TGS ticket requests with RC4 encryption or Rubeus/GetUserSPNs tooling detected — Kerberoasting in progress.",
        severity="critical",
        tactic="Credential Access",
        technique_id="T1558.003",
        technique_name="Steal or Forge Kerberos Tickets: Kerberoasting",
        condition=_kerberoasting,
    ),
    DetectionRule(
        rule_id="RULE-036",
        name="Pass-the-Hash Attack Detected",
        description="NTLM hash used directly for authentication without knowing the plaintext password (Pass-the-Hash / Overpass-the-Hash).",
        severity="critical",
        tactic="Lateral Movement",
        technique_id="T1550.002",
        technique_name="Use Alternate Authentication Material: Pass the Hash",
        condition=_pass_the_hash,
    ),
    DetectionRule(
        rule_id="RULE-037",
        name="Process Injection Detected",
        description="Process hollowing, reflective DLL injection, or APC queue injection techniques detected via memory operation APIs.",
        severity="critical",
        tactic="Defense Evasion",
        technique_id="T1055",
        technique_name="Process Injection",
        condition=_process_injection,
    ),
    DetectionRule(
        rule_id="RULE-038",
        name="LOLBAS Execution (Living off the Land)",
        description="Abuse of legitimate Windows binaries (mshta, certutil, regsvr32, bitsadmin, etc.) for malicious code execution or download.",
        severity="high",
        tactic="Execution",
        technique_id="T1218",
        technique_name="System Binary Proxy Execution",
        condition=_lolbas_execution,
    ),
    DetectionRule(
        rule_id="RULE-039",
        name="DGA Domain Activity Detected",
        description="High-entropy domain labels or suspicious TLDs indicate Domain Generation Algorithm (DGA) malware communication.",
        severity="high",
        tactic="Command and Control",
        technique_id="T1568.002",
        technique_name="Dynamic Resolution: Domain Generation Algorithms",
        condition=_dga_detection,
    ),
    DetectionRule(
        rule_id="RULE-040",
        name="DNS Tunneling Detected",
        description="Long high-entropy subdomain labels or TXT/NULL DNS record abuse indicate DNS tunneling for C2 data exfiltration.",
        severity="critical",
        tactic="Command and Control",
        technique_id="T1071.004",
        technique_name="Application Layer Protocol: DNS",
        condition=_dns_tunneling_entropy,
    ),
    DetectionRule(
        rule_id="RULE-041",
        name="AS-REP Roasting Detected",
        description="Kerberos AS-REQ requests for accounts with pre-authentication disabled — offline hash cracking attempt.",
        severity="high",
        tactic="Credential Access",
        technique_id="T1558.004",
        technique_name="Steal or Forge Kerberos Tickets: AS-REP Roasting",
        condition=_as_rep_roasting,
    ),
    DetectionRule(
        rule_id="RULE-042",
        name="Container Escape Attempt",
        description="nsenter targeting host PID 1, privileged container abuse, or Docker socket exploitation detected.",
        severity="critical",
        tactic="Privilege Escalation",
        technique_id="T1611",
        technique_name="Escape to Host",
        condition=_container_escape,
    ),
    DetectionRule(
        rule_id="RULE-043",
        name="Cloud IMDS Credential Theft",
        description="Access to AWS/Azure/GCP instance metadata service endpoint to steal IAM role credentials.",
        severity="critical",
        tactic="Credential Access",
        technique_id="T1552.005",
        technique_name="Unsecured Credentials: Cloud Instance Metadata API",
        condition=_cloud_imds_abuse,
    ),
    DetectionRule(
        rule_id="RULE-044",
        name="Ransomware Activity Detected",
        description="Ransom note creation, mass file encryption, backup service termination, or defender disabling — strong ransomware indicators.",
        severity="critical",
        tactic="Impact",
        technique_id="T1486",
        technique_name="Data Encrypted for Impact",
        condition=_ransomware_indicators,
    ),
    DetectionRule(
        rule_id="RULE-045",
        name="Volume Shadow Copy Deletion",
        description="vssadmin/wmic delete shadows command detected — ransomware or wiper attempting to prevent recovery.",
        severity="critical",
        tactic="Impact",
        technique_id="T1490",
        technique_name="Inhibit System Recovery",
        condition=_shadow_copy_deletion,
    ),
    DetectionRule(
        rule_id="RULE-046",
        name="Golden / Silver Ticket Forging",
        description="Mimikatz kerberos::golden or kerberos::silver command detected — complete domain compromise via forged Kerberos tickets.",
        severity="critical",
        tactic="Privilege Escalation",
        technique_id="T1558.001",
        technique_name="Steal or Forge Kerberos Tickets: Golden Ticket",
        condition=_golden_ticket,
    ),
]
